# Generated by Django 6.0.1 on 2026-02-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_DBMS', '0002_alter_student_created_at_alter_student_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
